# Generated by Django 2.1.5 on 2019-03-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
